build: false

clone_depth: 5

environment:
  matrix:
    - PYTHON: "C:/Python27"
      TOXENV: "py27"
    - PYTHON: "C:/Python35"
      TOXENV: "py35"
    - PYTHON: "C:/Python36"
      TOXENV: "py36"
    - PYTHON: "C:/Python37"
      TOXENV: "py37"
    - PYTHON: "C:/Python37"
      TOXENV: "lint"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  # Setup Python test tools
  - "SET STATIC_DEPS=true"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip setuptools wheel"
  - "python -m pip install -U virtualenv tox codecov"

test_script:
  - pip --version
  - virtualenv --version
  - tox --version
  - tox

after_test:
  - if not ("%TOXENV%" == "lint") if not ("%TOXENV%" == "documents") codecov

matrix:
  fast_finish: true
